version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    call dotnet restore

    call dotnet build .\ZopaTest.App\ZopaTest.App.csproj -f netcoreapp2.0 -c Release -r win-x64 -o ..\build-output\win-x64\ZopaTest
test_script:
- cmd: >-
    call dotnet restore

    call dotnet test .\ZopaTest.Tests\
notifications:
- provider: Slack
  incoming_webhook: 
    secure: 9v4gnDq4zFsnuGmkFNe7wN3KHW+DtMmvh2xyjLwUaz608HGzFc0cDFdsKZiq4kqK/urR6zYrWhJeNDoLjSRAJgjCXQaOVSCe+TRUthNujxg=
  channel: zopa-test
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true